-- Add CONDITION_REPORT_SUBMITTED and CONDITION_REPORT_APPROVED to NotificationEventType
ALTER TYPE "NotificationEventType" ADD VALUE 'CONDITION_REPORT_SUBMITTED';
ALTER TYPE "NotificationEventType" ADD VALUE 'CONDITION_REPORT_APPROVED';
