/**
 * English display labels for ASLOCA depreciation standard topic keys.
 *
 * Keys are the canonical UPPER_SNAKE_CASE topic values stored in the DB.
 * Values are human-readable English names shown in dropdowns and tables.
 *
 * Source: ASLOCA / FRI joint depreciation table, 2007 edition.
 */
export const TOPIC_EN = {
  // 1. Heating
  BOILER: "Boiler",
  BURNER: "Burner",
  HEATING_CONTROL: "Heating control unit",
  CIRCULATION_PUMP: "Circulation pump",
  CHIMNEY_CHROME_STEEL: "Flue pipe — chrome steel",
  CHIMNEY_GLASS_CERAMIC: "Flue pipe — glass ceramic",
  HEAT_PUMP: "Heat pump",
  DISTRICT_HEATING_CONVERTER: "District heating converter",
  SOLAR_PANEL: "Solar thermal panel",
  UNDERFLOOR_HEATING: "Underfloor heating",
  RADIATOR: "Radiator",
  TOWEL_RADIATOR: "Towel rail / radiator",
  HEATING_PIPES: "Heating pipes (copper/steel/cast iron)",
  HEATING_PAINT_SYNTHETIC: "Heating paint — synthetic resin",
  HEATING_VARNISH_THERMOLAC: "Heating varnish — thermolac",
  BOILER_ROOM_ELECTRICS: "Boiler room electrical installation",
  OIL_TANK_INDOOR: "Indoor oil tank",
  OIL_TANK_UNDERGROUND: "Underground oil tank",
  TANK_LEAK_PROTECTION: "Tank leak protection",
  HEAT_METER: "Heat / volume / flow meter",
  HEATING_COST_ALLOCATOR: "Heating cost allocator",
  THERMOSTATIC_VALVE: "Thermostatic valve",
  RADIATOR_VALVE: "Standard radiator valve",
  AIR_CONDITIONER: "Individual air conditioner",
  CONTROLLED_VENTILATION: "Controlled mechanical ventilation",
  // 2. Hot water
  WATER_HEATER_COMBINED: "Combined water heater (with heating)",
  WATER_HEATER_ELECTRIC: "Electric water heater",
  WATER_HEATER_GAS: "Gas water heater",
  // 3. Fireplace
  FIREPLACE: "Fireplace / stove",
  FIREPLACE_REFRACTORY_LINING: "Refractory brick lining",
  HOT_AIR_FIREPLACE: "Hot-air fireplace",
  SMOKE_EXTRACTION_FAN: "Smoke extraction fan",
  HOT_AIR_MOTOR: "Hot-air fireplace motor",
  HEAT_RECOVERY_MOTOR: "Heat recovery motor",
  FIREPLACE_SCREEN: "Fireplace screen / grille / glass",
  // 4. Building envelope
  INSULATION_POLYSTYRENE: "Polystyrene insulation (EPS)",
  INSULATION_GLASS_WOOL: "Glass wool insulation panels",
  FACADE_WOOD: "Ventilated wood facade",
  FACADE_PANELS: "Ventilated panel facade",
  FACADE_ETERNIT: "Eternit shingle facade",
  RENDER_MINERAL: "Mineral render (facade)",
  RENDER_SYNTHETIC: "Synthetic render (facade)",
  FACADE_PAINT_SILICATE: "Silicate paint (facade)",
  FACADE_PAINT_DISPERSION: "Dispersion paint (facade)",
  INSULATION_ROOF_ATTIC_CELLAR: "Roof / attic / cellar insulation",
  WINDOW_SILL_INSULATED: "Insulated window sill",
  EXTERIOR_ELASTIC_JOINTS: "Exterior elastic joints",
  WINDOW_DOUBLE_WOOD: "Double-glazed wood windows",
  WINDOW_INSULATED_PLASTIC_WOOD: "Insulated plastic / wood windows",
  WINDOW_INSULATED_METAL: "Insulated metal windows",
  WINDOW_FRAME_PAINT: "Window frame / sill paint",
  WINDOW_RUBBER_SEALS: "Window rubber seals",
  ROLLER_SHUTTER_PLASTIC: "Plastic roller shutters",
  ROLLER_SHUTTER_WOOD: "Wood roller shutters",
  ROLLER_SHUTTER_METAL: "Metal / aluminium roller shutters",
  BLINDS_PLASTIC: "Plastic venetian blinds",
  BLINDS_EXTERIOR_METAL: "Exterior metal blinds",
  BLINDS_INTERIOR: "Interior blinds (alu / plastic)",
  SHUTTER_STRAPS: "Shutter / blind straps",
  SHUTTERS_WOOD: "Wood shutters",
  SHUTTERS_WOOD_REPAINTED: "Repainted wood shutters",
  SHUTTERS_METAL: "Metal / aluminium shutters",
  SHUTTER_MOTORS: "Shutter / blind motors",
  WINDOW_CRANKS: "Window crank handles",
  CRANK_BRACKET_METAL: "Metal crank bracket",
  CRANK_BRACKET_PLASTIC: "Plastic crank bracket",
  FLAT_ROOF_GRAVEL: "Flat roof — gravel bound",
  FLAT_ROOF_CEMENT_TILES: "Flat roof — cement tiles",
  PITCHED_ROOF_TILES: "Pitched roof tiles / eternit",
  TINWORK_PAINTED: "Tinwork — painted / galvanised",
  TINWORK_COPPER_ZINC: "Tinwork — copper / titanium / zinc",
  TINWORK_STEEL: "Tinwork — steel / stainless / copper",
  CANOPY_METAL: "Canopy — metal structure",
  CANOPY_WOOD: "Canopy — wood structure",
  CANOPY_GLASS_REINFORCED: "Canopy — reinforced glass cover",
  CANOPY_SAFETY_GLASS: "Canopy — safety glass cover",
  CANOPY_TILE: "Canopy — tile cover",
  CANOPY_SHEET_METAL: "Canopy — sheet metal cover",
  // 5. Interior
  WALLPAPER_MEDIUM: "Wallpaper — standard quality",
  WALLPAPER_GOOD: "Wallpaper — washable quality",
  WALLPAPER_FIBREGLASS: "Fibreglass wallpaper",
  PAINT_WALLS_DISPERSION: "Wall paint — dispersion / acrylic",
  PAINT_WALLS_ALKYD: "Wall paint — alkyd / synthetic resin",
  PLASTER_PLASTIC: "Plastic plaster",
  PLASTER_MINERAL_RUSTIC: "Mineral rustic plaster",
  PLASTER_WHITE: "White plaster",
  PANELLING_RAW: "Raw wood panelling",
  PANELLING_STAINED: "Stained wood panelling",
  PANELLING_PAINTED: "Painted wood panelling",
  PANELLING_COATING: "Panelling stain / paint coat",
  CEILING_METAL_SUSPENDED: "Suspended metal ceiling with lighting",
  CEILING_WOOD_PANEL: "Wood panel ceiling",
  CEILING_WOOD_SUSPENDED: "Suspended wood ceiling",
  PARTITION_WALL_LIGHT: "Lightweight partition wall (alu / glass)",
  BUILT_IN_WARDROBE_CHIPBOARD: "Built-in wardrobe — chipboard",
  BUILT_IN_WARDROBE_SOLID: "Built-in wardrobe — solid wood",
  WARDROBE_HARDWARE: "Wardrobe hardware (locks / hinges)",
  WARDROBE_PAINT: "Wardrobe paint — oil / synthetic",
  DOOR_SOLID_WOOD: "Door — solid wood",
  DOOR_CHIPBOARD: "Door — chipboard / fibre",
  DOOR_METAL: "Door — metal",
  DOOR_PAINT: "Door paint — oil / synthetic",
  DOOR_GLASS_FRAME: "Door glass frame",
  DOOR_HARDWARE: "Door hardware (locks / hinges)",
  DOOR_RUBBER_SEALS: "Door rubber seals",
  SLIDING_DOOR: "Sliding / folding door",
  SLIDING_DOOR_ROLLERS: "Sliding door rollers",
  FRAME_WOOD_INTERIOR: "Interior wood frames / surrounds",
  FRAME_METAL_STONE: "Interior metal / stone frames",
  WINDOWSILL_INTERIOR_LACQUERED: "Interior lacquered window sill",
  AUTO_CLOSER: "Automatic door closer",
  LOCK_ENTRY_DOOR: "Entry door lock",
  LOCK_INTERIOR: "Interior door locks",
  DOOR_JOINTS: "Door joints",
  // 6. Flooring
  FLOOR_PVC: "PVC / vinyl flooring",
  FLOOR_RUBBER: "Rubber flooring",
  FLOOR_LINOLEUM: "Linoleum flooring",
  FLOOR_CORK: "Glazed cork flooring",
  FLOOR_LAMINATE_31: "Laminate class 31 (economy)",
  FLOOR_LAMINATE_32: "Laminate class 32 (standard)",
  FLOOR_LAMINATE_33: "Laminate class 33 (premium)",
  PARQUET_MOSAIC: "Glued solid parquet (mosaic format)",
  PARQUET_SURFACE_TREATMENT: "Parquet varnish / oil treatment",
  FLOOR_SUBSTRATE: "Floor substrate (hardboard / MDF)",
  RAISED_FLOOR: "Raised technical floor",
  TILES_TERRACOTTA: "Terracotta tiles",
  TILES_NATURAL_STONE_SOFT: "Natural soft stone (marble etc.)",
  TILES_NATURAL_STONE_HARD: "Natural hard stone (granite etc.)",
  TILES_CERAMIC_GLAZED: "Glazed ceramic tiles",
  TILES_PORCELAIN_STONEWARE: "Porcelain stoneware tiles",
  TILES_ARTIFICIAL_STONE: "Artificial stone tiles",
  CARPET_NATURAL: "Natural fibre carpet (sisal / coco)",
  CARPET_KUGELGARN: "Loop-pile carpet",
  CARPET_NEEDLE_FELT: "Needle-felt carpet",
  CARPET_MEDIUM: "Standard carpet",
  SKIRTING_PLASTIC: "Plastic / veneer skirting boards",
  SKIRTING_HARDWOOD: "Hardwood skirting boards",
  FLOOR_JOINTS: "Floor joints",
  // 7. Kitchen
  FRIDGE: "Fridge-freezer (combined)",
  FREEZER: "Standalone freezer",
  GAS_COOKER: "Built-in gas cooker with oven",
  CERAMIC_HOB: "Ceramic hob",
  INDUCTION_HOB: "Induction hob",
  COOKER_OVEN: "Cooker and oven",
  ELECTRIC_HOB: "Conventional electric hob",
  DISHWASHER: "Dishwasher",
  KITCHEN_HOOD: "Extractor hood with filter",
  MICROWAVE: "Microwave oven",
  STEAMER: "Steamer / combi-steamer",
  KITCHEN_CABINET_CHIPBOARD: "Kitchen units — chipboard / MDF",
  KITCHEN_CABINET_METAL: "Kitchen units — thermolac metal",
  KITCHEN_CABINET_SOLID: "Kitchen units — solid wood",
  COUNTERTOP_STONE_STEEL: "Worktop — stone / steel / glass",
  COUNTERTOP_SYNTHETIC: "Worktop — synthetic resin",
  COUNTERTOP_WOOD: "Worktop — wood / chipboard",
  KITCHEN_TAP: "Kitchen tap / faucet",
  KITCHEN_VENT_GRILLE: "Lower ventilation grille",
  KITCHEN_RENOVATION_BASIC: "Full kitchen renovation (standard)",
  KITCHEN_RENOVATION_PREMIUM: "Full kitchen renovation (premium)",
  KITCHEN_TILES_CERAMIC: "Glazed ceramic kitchen tiles",
  KITCHEN_TILES_STONEWARE: "Stoneware / mosaic kitchen tiles",
  KITCHEN_TILES_PORCELAIN: "Porcelain kitchen tiles",
  KITCHEN_JOINTS: "Kitchen sealant / joints",
  // 8. Bathroom
  BATHTUB_ACRYLIC: "Acrylic bathtub",
  BATHTUB_STEEL: "Enamelled steel bathtub",
  BATHTUB_REENAMELLING: "Bathtub / shower re-enamelling",
  SANITARY_CERAMIC: "Ceramic WC / basin / bidet",
  SHOWER_WC: "Shower-toilet (Clos-o-mat)",
  FLUSH_CONCEALED: "Concealed cistern",
  FLUSH_EXPOSED_PLASTIC: "Exposed plastic cistern",
  FLUSH_EXPOSED_CERAMIC: "Exposed ceramic cistern",
  WASHING_MACHINE_PRIVATE: "Washing machine (in-unit)",
  DRYER_PRIVATE: "Tumble dryer (in-unit)",
  MEDICINE_CABINET_PLASTIC: "Medicine cabinet — plastic",
  MEDICINE_CABINET_CHIPBOARD: "Medicine cabinet — chipboard",
  MEDICINE_CABINET_METAL: "Medicine cabinet — lacquered metal",
  BATHROOM_MIRROR: "Bathroom mirror",
  BATHROOM_FURNITURE_PLASTIC: "Bathroom furniture — plastic",
  BATHROOM_FURNITURE_CHIPBOARD: "Bathroom furniture — chipboard",
  BATHROOM_FURNITURE_METAL: "Bathroom furniture — thermolac metal",
  SHOWER_CABIN_PLASTIC: "Shower cabin — plastic",
  SHOWER_CABIN_GLASS: "Shower cabin — glass",
  BATHROOM_TAP: "Chrome tap with mixer",
  TAP_JOINTS: "Tap joints / seals",
  BATHROOM_TILES_CERAMIC: "Glazed ceramic bathroom tiles",
  BATHROOM_TILES_STONEWARE: "Stoneware / mosaic bathroom tiles",
  BATHROOM_TILES_PORCELAIN: "Porcelain bathroom tiles",
  BATHROOM_JOINTS: "Bathroom sealant / joints",
  GAS_WATER_HEATER: "Gas water heater (bathroom)",
  BATHROOM_FULL_RENOVATION: "Full bathroom renovation",
  // 9. Plumbing
  PIPE_COLD_GALVANISED: "Cold water pipes — galvanised steel",
  PIPE_COLD_CHROME: "Cold water pipes — chrome steel",
  PIPE_COLD_COPPER: "Cold water pipes — copper",
  PIPE_PEX_METAL: "Water pipes — PEX / metal",
  PIPE_HOT_COPPER_INSULATED: "Hot water pipes — insulated copper",
  PIPE_GAS_STEEL: "Gas pipes — painted steel",
  // 9b. Electrical
  TV_CABLE_SOCKET: "TV cable socket",
  ISDN_SOCKET: "ISDN / data socket",
  TV_ANTENNA: "TV / satellite antenna",
  PHONE_DISTRIBUTION: "Telephone distribution unit",
  PHONE_EXCHANGE: "Telephone exchange / PABX",
  SWITCH: "Light switch",
  POWER_SOCKET: "Power socket",
  LAMP_SOCKET: "Lamp socket",
  ELECTRICITY_METER: "Electricity meter",
  LIGHTING_KITCHEN_BATH: "Kitchen / bathroom / WC lighting",
  ELECTRICAL_CABLES: "Electrical cables",
  HIGH_VOLTAGE_INSTALL: "High-voltage electrical installation",
  // 10. Exterior
  BALCONY_WOOD: "Balcony — wood structure",
  BALCONY_METAL: "Balcony — metal structure",
  BALCONY_TILES_CEMENT: "Balcony cement tiles",
  BALCONY_TILES_PORCELAIN: "Balcony porcelain tiles",
  BALCONY_RAILING_WOOD: "Balcony railing — painted wood",
  BALCONY_RAILING_METAL: "Balcony railing — painted / thermolac metal",
  AWNING_FABRIC: "Fabric awning",
  AWNING_STRAPS: "Awning straps",
  CONSERVATORY_WOOD: "Conservatory — wood / plastic + glazing",
  CONSERVATORY_STEEL: "Conservatory — painted steel + glazing",
  CONSERVATORY_ALU: "Conservatory — alu / galvanised steel + glazing",
  TERRACE_RAILING_WOOD: "Terrace railing — painted wood",
  TERRACE_RAILING_METAL: "Terrace railing — metal",
  TERRACE_TILES_CEMENT: "Terrace cement tiles",
  TERRACE_TILES_PORCELAIN: "Terrace porcelain tiles",
  TERRACE_ELECTRICS: "Terrace electrical installation",
  GARDEN_BENCH: "Garden bench (eternit / wood)",
  PLAYGROUND_EQUIPMENT: "Playground equipment",
  DOORMAT: "Doormat / scraper",
  // 11. Cellar & attic
  CELLAR_HABITABLE: "Cellar / attic (habitable use)",
  CELLAR_STORAGE: "Cellar / attic (storage use)",
  SHELTER_VENTILATION: "Shelter ventilation",
  // 12. Elevator
  ELEVATOR: "Elevator",
  ELEVATOR_ELECTRICS: "Elevator electrical installation",
  // 13. Common areas
  WASHING_MACHINE_COMMON: "Washing machine (communal)",
  DRYER_COMMON: "Tumble dryer (communal)",
  AIR_DRYER_COMMON: "Hot-air tumble dryer (communal)",
  WATER_SOFTENER: "Water softener",
  COMBINED_LOCK_SYSTEM: "Combined locking system",
  AUTO_DOORS: "Automatic doors",
  INTERCOM: "Intercom",
  MAILBOXES: "Mailboxes",
  FENCE_LIGHT: "Light fence (metal / wood posts)",
  FENCE_METAL_MESH: "Metal mesh fence",
  BOUNDARY_WALL: "Garden / garage / boundary wall",
  ACCESS_PATH_CONCRETE: "Concrete access path",
};

/** Return the English display name for a topic key, falling back to title-casing. */
export function topicLabel(key) {
  return (
    TOPIC_EN[key] ||
    key.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())
  );
}
