/**
 * chargeReconciliationService
 *
 * Business logic for ACOMPTE year-end charge reconciliation.
 *
 * Architecture: service layer — uses repositories, never calls Prisma directly
 * except for invoice-line-item queries needed for ACOMPTE summation.
 *
 * Key business rules:
 *  - Only ACOMPTE expense items are reconciled (FORFAIT = flat-rate, no settlement).
 *  - ACOMPTE paid is auto-calculated from invoices generated by the billing schedule
 *    for the given fiscal year.
 *  - Manager enters actual costs per expense category.
 *  - Settlement invoice is created on "settle" — positive balance = tenant debit,
 *    negative balance = tenant credit.
 */

import { PrismaClient } from "@prisma/client";
import * as reconRepo from "../repositories/chargeReconciliationRepository";
import { issueInvoiceWorkflow } from "../workflows/issueInvoiceWorkflow";
import type { WorkflowContext } from "../workflows/context";

// ─── Create Reconciliation ─────────────────────────────────────

export interface CreateReconciliationInput {
  orgId: string;
  leaseId: string;
  fiscalYear: number;
}

/**
 * Create a new charge reconciliation for a lease + fiscal year.
 *
 * Auto-populates:
 *  1. Line items from the lease's active expense items
 *  2. ACOMPTE paid amounts from invoices generated during the fiscal year
 *     (only invoices linked to the lease with billing periods in the fiscal year)
 */
export async function createReconciliation(
  prisma: PrismaClient,
  input: CreateReconciliationInput,
) {
  const { orgId, leaseId, fiscalYear } = input;

  // Check for existing reconciliation
  const existing = await reconRepo.findByLeaseAndYear(prisma, leaseId, fiscalYear);
  if (existing) {
    throw new Error(`Reconciliation already exists for this lease and year ${fiscalYear}`);
  }

  // Fetch lease with expense items
  const lease = await prisma.lease.findUnique({
    where: { id: leaseId },
    include: {
      expenseItems: {
        where: { isActive: true },
        select: {
          id: true,
          description: true,
          amountChf: true,
          mode: true,
        },
      },
    },
  });

  if (!lease) throw new Error("Lease not found");
  if (lease.orgId !== orgId) throw new Error("Lease does not belong to this org");

  // Calculate ACOMPTE paid per expense item from generated invoices
  // We look at invoice line items for invoices that:
  //   - belong to this lease
  //   - have a billingPeriodStart within the fiscal year
  //   - are in a non-DRAFT status (ISSUED, APPROVED, or PAID)
  const yearStart = new Date(fiscalYear, 0, 1);   // Jan 1
  const yearEnd = new Date(fiscalYear, 11, 31);    // Dec 31

  const invoicesInYear = await prisma.invoice.findMany({
    where: {
      leaseId,
      billingPeriodStart: { gte: yearStart, lte: yearEnd },
      status: { in: ["ISSUED", "APPROVED", "PAID"] },
    },
    include: {
      lineItems: {
        select: {
          description: true,
          lineTotal: true,
        },
      },
    },
  });

  // Build a map of expense description → total ACOMPTE paid (cents)
  // Invoice line item descriptions follow the pattern:
  //   "Heating (acompte)" or "Heating (acompte, pro rata)"
  const acomptePaidMap = new Map<string, number>();

  for (const inv of invoicesInYear) {
    for (const li of inv.lineItems) {
      // Skip the base rent line (contains "Loyer net")
      if (li.description.includes("Loyer net")) continue;

      // Extract the base description — strip mode labels and pro-rata text
      // Line items look like: "Heating (acompte)" or "Water (acompte, pro rata)"
      const baseDesc = li.description
        .replace(/\s*\(acompte(?:,?\s*pro rata)?\)\s*$/i, "")
        .replace(/\s*\(forfait(?:,?\s*pro rata)?\)\s*$/i, "")
        .trim();

      if (baseDesc) {
        acomptePaidMap.set(baseDesc, (acomptePaidMap.get(baseDesc) ?? 0) + li.lineTotal);
      }
    }
  }

  // Build line items from lease expense items
  const lineItems = lease.expenseItems.map((item) => ({
    description: item.description,
    chargeMode: item.mode as "ACOMPTE" | "FORFAIT",
    acomptePaidCents: acomptePaidMap.get(item.description) ?? 0,
  }));

  if (lineItems.length === 0) {
    throw new Error("No expense items found on this lease — nothing to reconcile");
  }

  return reconRepo.createReconciliation(prisma, {
    orgId,
    leaseId,
    fiscalYear,
    lineItems,
  });
}

// ─── Update Line ───────────────────────────────────────────────

/**
 * Update the actual cost for a reconciliation line item.
 * Only allowed while the reconciliation is in DRAFT status.
 */
export async function updateLineActualCost(
  prisma: PrismaClient,
  reconciliationId: string,
  lineId: string,
  actualCostCents: number,
  orgId: string,
) {
  const recon = await reconRepo.findById(prisma, reconciliationId, orgId);
  if (!recon) throw new Error("Reconciliation not found");
  if (recon.status !== "DRAFT") {
    throw new Error(`Cannot edit a ${recon.status} reconciliation`);
  }

  // Verify line belongs to this reconciliation
  const line = recon.lineItems.find((l) => l.id === lineId);
  if (!line) throw new Error("Line item not found in this reconciliation");

  return reconRepo.updateLineActualCost(prisma, lineId, actualCostCents);
}

// ─── Finalize ──────────────────────────────────────────────────

/**
 * Finalize a reconciliation: recalculate balances and lock for settlement.
 * Manager must have entered actual costs for all ACOMPTE lines.
 */
export async function finalizeReconciliation(
  prisma: PrismaClient,
  reconciliationId: string,
  orgId: string,
) {
  const recon = await reconRepo.findById(prisma, reconciliationId, orgId);
  if (!recon) throw new Error("Reconciliation not found");
  if (recon.status !== "DRAFT") {
    throw new Error(`Cannot finalize a ${recon.status} reconciliation`);
  }

  // Validate: all ACOMPTE lines must have actual costs > 0 entered
  const acompteLines = recon.lineItems.filter((l) => l.chargeMode === "ACOMPTE");
  const missingCosts = acompteLines.filter((l) => l.actualCostCents === 0);
  if (missingCosts.length > 0) {
    throw new Error(
      `Actual costs missing for: ${missingCosts.map((l) => l.description).join(", ")}`,
    );
  }

  return reconRepo.finalizeReconciliation(prisma, reconciliationId);
}

// ─── Settle (Generate Invoice) ─────────────────────────────────

/**
 * Settle a finalized reconciliation by generating a settlement invoice.
 *
 * If balanceCents > 0: tenant owes more → OUTGOING debit invoice.
 * If balanceCents < 0: tenant overpaid → OUTGOING credit invoice (negative amount).
 * If balanceCents = 0: no settlement needed (but we still mark as settled).
 */
export async function settleReconciliation(
  prisma: PrismaClient,
  reconciliationId: string,
  orgId: string,
) {
  const recon = await reconRepo.findById(prisma, reconciliationId, orgId);
  if (!recon) throw new Error("Reconciliation not found");
  if (recon.status !== "FINALIZED") {
    throw new Error(`Cannot settle a ${recon.status} reconciliation — must be FINALIZED first`);
  }

  const lease = recon.lease;
  if (!lease) throw new Error("Lease not found for reconciliation");

  const balance = recon.balanceCents;

  // If balance is 0, just mark settled without generating an invoice
  if (balance === 0) {
    return reconRepo.settleReconciliation(prisma, reconciliationId, "");
  }

  const isDebit = balance > 0;
  const absBalance = Math.abs(balance);

  // Build invoice description
  const description = isDebit
    ? `Décompte de charges ${recon.fiscalYear} — solde à payer`
    : `Décompte de charges ${recon.fiscalYear} — solde en faveur du locataire`;

  // Build line items: one per ACOMPTE expense item with a non-zero balance
  const acompteLines = recon.lineItems.filter(
    (l) => l.chargeMode === "ACOMPTE" && l.balanceCents !== 0,
  );

  const invoiceLineItems = acompteLines.map((line) => {
    const lineBalance = line.actualCostCents - line.acomptePaidCents;
    return {
      description: `${line.description} — réel ${(line.actualCostCents / 100).toFixed(2)} CHF, acomptes ${(line.acomptePaidCents / 100).toFixed(2)} CHF`,
      quantity: 1,
      unitPrice: Math.abs(lineBalance),
      vatRate: 0,
      lineTotal: Math.abs(lineBalance),
    };
  });

  // Resolve issuer billing entity
  let issuerBillingEntityId: string | undefined;
  if (lease.unitId) {
    const unit = await prisma.unit.findUnique({
      where: { id: lease.unitId },
      select: {
        building: {
          select: {
            owners: {
              include: { user: { select: { billingEntity: { select: { id: true } } } } },
              take: 1,
            },
          },
        },
      },
    });
    issuerBillingEntityId = unit?.building?.owners?.[0]?.user?.billingEntity?.id ?? undefined;
  }
  if (!issuerBillingEntityId) {
    const orgBillingEntity = await prisma.billingEntity.findFirst({
      where: { orgId, type: "ORG" },
      select: { id: true },
    });
    issuerBillingEntityId = orgBillingEntity?.id;
  }

  // Due date = 30 days from now
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 30);

  // Create the settlement invoice
  const invoice = await prisma.invoice.create({
    data: {
      orgId,
      leaseId: lease.id,
      description,
      subtotalAmount: absBalance,
      vatAmount: 0,
      totalAmount: absBalance,
      amount: Math.round(absBalance / 100),
      currency: "CHF",
      vatRate: 0,
      status: "DRAFT",
      direction: "OUTGOING",
      sourceChannel: "MANUAL",
      recipientName: lease.tenantName,
      recipientAddressLine1: "",
      recipientPostalCode: "",
      recipientCity: "",
      recipientCountry: "CH",
      issuerBillingEntityId: issuerBillingEntityId || null,
      billingPeriodStart: new Date(recon.fiscalYear, 0, 1),
      billingPeriodEnd: new Date(recon.fiscalYear, 11, 31),
      lineItems: {
        create: invoiceLineItems,
      },
    },
  });

  // Issue the invoice via workflow
  const ctx: WorkflowContext = {
    orgId,
    prisma,
    actorUserId: null,
  };

  try {
    await issueInvoiceWorkflow(ctx, {
      invoiceId: invoice.id,
      issuerBillingEntityId,
      issueDate: new Date(),
      dueDate,
    });
  } catch (err) {
    console.error(
      `[CHARGE-RECONCILIATION] Failed to issue settlement invoice ${invoice.id}:`,
      err,
    );
  }

  // Link the invoice to the reconciliation and mark as settled
  return reconRepo.settleReconciliation(prisma, reconciliationId, invoice.id);
}

// ─── Reopen ────────────────────────────────────────────────────

/**
 * Reopen a FINALIZED reconciliation back to DRAFT for corrections.
 * Cannot reopen once SETTLED.
 */
export async function reopenReconciliation(
  prisma: PrismaClient,
  reconciliationId: string,
  orgId: string,
) {
  const recon = await reconRepo.findById(prisma, reconciliationId, orgId);
  if (!recon) throw new Error("Reconciliation not found");
  if (recon.status === "SETTLED") {
    throw new Error("Cannot reopen a settled reconciliation");
  }

  return prisma.chargeReconciliation.update({
    where: { id: reconciliationId },
    data: { status: "DRAFT" },
    include: reconRepo.RECONCILIATION_INCLUDE,
  });
}
