import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import AppShell from "../../components/AppShell";
import PageShell from "../../components/layout/PageShell";
import PageHeader from "../../components/layout/PageHeader";
import PageContent from "../../components/layout/PageContent";
import Panel from "../../components/layout/Panel";
import ErrorBanner from "../../components/ui/ErrorBanner";
import Badge from "../../components/ui/Badge";
import { rfpVariant } from "../../lib/statusVariants";
import { authHeaders } from "../../lib/api";

import { cn } from "../../lib/utils";
const STATUS_TABS = [
  { key: "ALL", label: "All" },
  { key: "DRAFT", label: "Draft" },
  { key: "OPEN", label: "Open" },
  { key: "EVALUATING", label: "Evaluating" },
  { key: "AWARDED", label: "Awarded" },
  { key: "CANCELLED", label: "Cancelled" },
];

function formatDate(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("de-CH");
}

export default function ManagerRfpsPage() {
  const router = useRouter();
  const [rfps, setRfps] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("ALL");

  const loadData = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const params = activeTab !== "ALL" ? `?status=${activeTab}` : "";
      const res = await fetch(`/api/rfps${params}`, { headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error?.message || "Failed to load RFPs");
      setRfps(data?.data || []);
      setTotal(data?.total ?? data?.data?.length ?? 0);
    } catch (e) {
      setError(String(e?.message || e));
    } finally {
      setLoading(false);
    }
  }, [activeTab]);

  useEffect(() => { loadData(); }, [loadData]);

  return (
    <AppShell role="MANAGER">
      <PageShell>
        <PageHeader
          title="Requests for Proposal"
          subtitle="Manage RFPs generated by the legal decision engine"
        />
        <PageContent>
          <ErrorBanner error={error} className="text-sm" />

          {/* Status tabs */}
          <div className="flex gap-1 rounded-lg border border-slate-200 bg-white p-1">
            {STATUS_TABS.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={cn("rounded-lg px-3 py-1.5 text-sm font-medium transition-colors", activeTab === tab.key
                    ? "bg-blue-600 text-white"
                    : "text-slate-600 hover:bg-slate-100")}
              >
                {tab.label}
              </button>
            ))}
          </div>

          <Panel title={`RFPs (${total})`} bodyClassName="p-0">
            {loading ? (
              <p className="px-4 py-8 text-center text-sm text-slate-500">Loading…</p>
            ) : rfps.length === 0 ? (
              <p className="px-4 py-8 text-center text-sm text-slate-400">
                No RFPs found{activeTab !== "ALL" ? ` with status ${activeTab}` : ""}. RFPs are created automatically when the legal engine determines an obligation.
              </p>
            ) : (
              <table className="inline-table">
                <thead>
                  <tr>
                    <th>Request</th>
                    <th>Category</th>
                    <th>Building / Unit</th>
                    <th>Status</th>
                    <th>Invites</th>
                    <th>Quotes</th>
                    <th>Created</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {rfps.map((rfp) => (
                    <tr
                      key={rfp.id}
                      className="cursor-pointer hover:bg-slate-50/80"
                      onClick={() => router.push(`/manager/rfps/${rfp.id}`)}
                    >
                      <td>
                        {rfp.request ? (
                          <span className="text-sm">
                            <span className="font-medium text-slate-900">
                              #{rfp.request.requestNumber}
                            </span>
                            <span className="block text-xs text-slate-500 max-w-[200px] truncate">
                              {rfp.request.description}
                            </span>
                          </span>
                        ) : (
                          <span className="text-xs text-slate-400">No request linked</span>
                        )}
                      </td>
                      <td className="text-sm text-slate-700">{rfp.category || "—"}</td>
                      <td className="text-sm text-slate-700">
                        {rfp.building?.name || "—"}
                        {rfp.unit && (
                          <span className="text-slate-400"> / {rfp.unit.unitNumber}</span>
                        )}
                      </td>
                      <td>
                        <Badge variant={rfpVariant(rfp.status)} size="sm">
                          {rfp.status}
                        </Badge>
                      </td>
                      <td className="text-center text-sm text-slate-700">
                        {rfp.invites?.length ?? 0}
                      </td>
                      <td className="text-center text-sm text-slate-700">
                        <span className={rfp.quoteCount > 0 ? "font-medium text-green-700" : ""}>
                          {rfp.quoteCount ?? 0}
                        </span>
                      </td>
                      <td className="text-sm text-slate-500">{formatDate(rfp.createdAt)}</td>
                      <td>
                        <button
                          aria-label="View RFP"
                          onClick={(e) => {
                            e.stopPropagation();
                            router.push(`/manager/rfps/${rfp.id}`);
                          }}
                          className="inline-flex items-center justify-center rounded p-1 text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clipRule="evenodd" />
                          </svg>
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </Panel>
        </PageContent>
      </PageShell>
    </AppShell>
  );
}
