import { useEffect, useState, useCallback, useMemo } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import AppShell from "../../components/AppShell";
import PageShell from "../../components/layout/PageShell";
import PageHeader from "../../components/layout/PageHeader";
import PageContent from "../../components/layout/PageContent";
import Panel from "../../components/layout/Panel";
import ErrorBanner from "../../components/ui/ErrorBanner";
import Badge from "../../components/ui/Badge";
import { rfpVariant } from "../../lib/statusVariants";
import { authHeaders } from "../../lib/api";
import { formatDate } from "../../lib/format";
import ConfigurableTable from "../../components/ConfigurableTable";
import { useTableSort, clientSort } from "../../lib/tableUtils";

const STATUS_TABS = [
  { key: "ALL", label: "All" },
  { key: "DRAFT", label: "Draft" },
  { key: "OPEN", label: "Open" },
  { key: "EVALUATING", label: "Evaluating" },
  { key: "AWARDED", label: "Awarded" },
  { key: "CANCELLED", label: "Cancelled" },
];

const RFP_SORT_FIELDS = ["category", "status", "invites", "quotes", "createdAt"];

function rfpFieldExtractor(rfp, field) {
  switch (field) {
    case "category": return (rfp.category || "").toLowerCase();
    case "status": return rfp.status || "";
    case "invites": return rfp.invites?.length ?? 0;
    case "quotes": return rfp.quoteCount ?? 0;
    case "createdAt": return rfp.createdAt || "";
    default: return "";
  }
}

const RFP_COLUMNS = [
  {
    id: "request",
    label: "Request",
    alwaysVisible: true,
    render: (rfp) =>
      rfp.request ? (
        <span className="text-sm">
          <span className="font-medium text-slate-900">#{rfp.request.requestNumber}</span>
          <span className="block text-xs text-slate-500 max-w-[200px] truncate">{rfp.request.description}</span>
        </span>
      ) : (
        <span className="text-xs text-slate-400">No request linked</span>
      ),
  },
  {
    id: "category",
    label: "Category",
    sortable: true,
    defaultVisible: true,
    render: (rfp) => <span className="text-sm text-slate-700">{rfp.category || "\u2014"}</span>,
  },
  {
    id: "location",
    label: "Building / Unit",
    defaultVisible: true,
    render: (rfp) => (
      <span className="text-sm text-slate-700">
        {rfp.building?.name || "\u2014"}
        {rfp.unit && <span className="text-slate-400"> / {rfp.unit.unitNumber}</span>}
      </span>
    ),
  },
  {
    id: "status",
    label: "Status",
    sortable: true,
    defaultVisible: true,
    render: (rfp) => <Badge variant={rfpVariant(rfp.status)} size="sm">{rfp.status}</Badge>,
  },
  {
    id: "invites",
    label: "Invites",
    sortable: true,
    defaultVisible: true,
    className: "text-center",
    render: (rfp) => <span className="text-sm text-slate-700">{rfp.invites?.length ?? 0}</span>,
  },
  {
    id: "quotes",
    label: "Quotes",
    sortable: true,
    defaultVisible: true,
    className: "text-center",
    render: (rfp) => (
      <span className={rfp.quoteCount > 0 ? "font-medium text-green-700 text-sm" : "text-sm text-slate-700"}>
        {rfp.quoteCount ?? 0}
      </span>
    ),
  },
  {
    id: "createdAt",
    label: "Created",
    sortable: true,
    defaultVisible: true,
    render: (rfp) => <span className="text-sm text-slate-500">{formatDate(rfp.createdAt)}</span>,
  },
];

export default function ManagerRfpsPage() {
  const router = useRouter();
  const [rfps, setRfps] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("ALL");
  const { sortField, sortDir, handleSort } = useTableSort(router, RFP_SORT_FIELDS, { defaultField: "createdAt", defaultDir: "desc" });
  const sortedRfps = useMemo(() => clientSort(rfps, sortField, sortDir, rfpFieldExtractor), [rfps, sortField, sortDir]);

  const loadData = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const params = activeTab !== "ALL" ? `?status=${activeTab}` : "";
      const res = await fetch(`/api/rfps${params}`, { headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error?.message || "Failed to load RFPs");
      setRfps(data?.data || []);
      setTotal(data?.total ?? data?.data?.length ?? 0);
    } catch (e) {
      setError(String(e?.message || e));
    } finally {
      setLoading(false);
    }
  }, [activeTab]);

  useEffect(() => { loadData(); }, [loadData]);

  return (
    <AppShell role="MANAGER">
      <PageShell>
        <PageHeader
          title="Requests for Proposal"
          subtitle="Manage RFPs generated by the legal decision engine"
        />
        <PageContent>
          <div className="mb-4">
            <Link href="/manager" className="text-sm font-medium text-slate-600 hover:text-slate-900">
              ← Back to Dashboard
            </Link>
          </div>
          <ErrorBanner error={error} className="text-sm" />

          {/* Status tabs */}
          <div className="tab-strip">
            {STATUS_TABS.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={activeTab === tab.key ? "tab-btn-active" : "tab-btn"}
              >
                {tab.label}
              </button>
            ))}
          </div>

          <Panel title={`RFPs (${total})`} bodyClassName="p-0">
            {loading ? (
              <p className="px-4 py-8 text-center text-sm text-slate-500">Loading…</p>
            ) : (
              <ConfigurableTable
                tableId="manager-rfps"
                columns={RFP_COLUMNS}
                data={sortedRfps}
                rowKey={(rfp) => rfp.id}
                sortField={sortField}
                sortDir={sortDir}
                onSort={handleSort}
                onRowClick={(rfp) => router.push(`/manager/rfps/${rfp.id}`)}
                emptyState={
                  <p className="px-4 py-8 text-center text-sm text-slate-400">
                    No RFPs found{activeTab !== "ALL" ? ` with status ${activeTab}` : ""}. RFPs are created automatically when the legal engine determines an obligation.
                  </p>
                }
                mobileCard={(rfp) => (
                  <div className="table-card">
                    <div className="flex items-start justify-between gap-2">
                      <p className="table-card-head">#{rfp.request?.requestNumber || "—"}</p>
                      <Badge variant={rfpVariant(rfp.status)} size="sm">{rfp.status}</Badge>
                    </div>
                    {rfp.request?.description && <p className="table-card-sub truncate">{rfp.request.description}</p>}
                    <div className="table-card-footer">
                      {rfp.category && <span>{rfp.category}</span>}
                      {rfp.building?.name && <span>{rfp.building.name}{rfp.unit ? ` / ${rfp.unit.unitNumber}` : ""}</span>}
                      <span>{rfp.invites?.length ?? 0} invited · {rfp.quoteCount ?? 0} quotes</span>
                    </div>
                  </div>
                )}
              />
            )}
          </Panel>
        </PageContent>
      </PageShell>
    </AppShell>
  );
}
