import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import AppShell from "../../components/AppShell";
import PageShell from "../../components/layout/PageShell";
import PageHeader from "../../components/layout/PageHeader";
import PageContent from "../../components/layout/PageContent";
import Panel from "../../components/layout/Panel";
import { authHeaders } from "../../lib/api";

const STATUS_TABS = [
  { key: "ALL", label: "All" },
  { key: "OPEN", label: "Open" },
  { key: "EVALUATING", label: "Evaluating" },
  { key: "AWARDED", label: "Awarded" },
  { key: "CANCELLED", label: "Cancelled" },
];

export default function ManagerRfpsPage() {
  const [rfps, setRfps] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("ALL");

  const loadData = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const params = activeTab !== "ALL" ? `?status=${activeTab}` : "";
      const res = await fetch(`/api/rfps${params}`, { headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error?.message || "Failed to load RFPs");
      setRfps(data?.data || []);
    } catch (e) {
      setError(String(e?.message || e));
    } finally {
      setLoading(false);
    }
  }, [activeTab]);

  useEffect(() => { loadData(); }, [loadData]);

  return (
    <AppShell role="MANAGER">
      <PageShell>
        <PageHeader
          title="Requests for Proposal"
          subtitle="Manage RFPs generated by the legal decision engine"
        />
        <PageContent>
          {error && (
            <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {error}
            </div>
          )}

          {/* Status tabs */}
          <div className="flex gap-1 rounded-lg border border-slate-200 bg-white p-1">
            {STATUS_TABS.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
                  activeTab === tab.key
                    ? "bg-blue-600 text-white"
                    : "text-slate-600 hover:bg-slate-100"
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          <Panel title={`RFPs (${rfps.length})`}>
            {loading ? (
              <p className="text-sm text-slate-500">Loading…</p>
            ) : rfps.length === 0 ? (
              <p className="text-sm text-slate-500">
                No RFPs found{activeTab !== "ALL" ? ` with status ${activeTab}` : ""}. RFPs are created automatically when the legal engine determines an obligation.
              </p>
            ) : (
              <div className="space-y-3">
                {rfps.map((rfp) => (
                  <RfpCard key={rfp.id} rfp={rfp} />
                ))}
              </div>
            )}
          </Panel>
        </PageContent>
      </PageShell>
    </AppShell>
  );
}

function RfpCard({ rfp }) {
  const [expanded, setExpanded] = useState(false);

  const statusColors = {
    OPEN: "bg-blue-50 text-blue-700 border-blue-200",
    EVALUATING: "bg-yellow-50 text-yellow-700 border-yellow-200",
    AWARDED: "bg-green-50 text-green-700 border-green-200",
    CANCELLED: "bg-slate-50 text-slate-500 border-slate-200",
  };

  return (
    <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold text-slate-900">
              RFP {rfp.id?.slice(0, 8)}…
            </span>
            <span className={`inline-block rounded-full border px-2 py-0.5 text-xs font-medium ${statusColors[rfp.status] || statusColors.OPEN}`}>
              {rfp.status}
            </span>
          </div>
          <div className="flex flex-wrap gap-2 text-xs text-slate-500">
            {rfp.building && (
              <span>Building: <strong>{rfp.building.name || rfp.buildingId?.slice(0, 8)}</strong></span>
            )}
            {rfp.unit && (
              <><span>•</span><span>Unit: <strong>{rfp.unit.unitNumber || rfp.unitId?.slice(0, 8)}</strong></span></>
            )}
            <span>•</span>
            <span>Scope: <strong>{rfp.scope || "—"}</strong></span>
            <span>•</span>
            <span>Created: {formatDate(rfp.createdAt)}</span>
          </div>
          {rfp.awardedContractor && (
            <p className="text-xs text-green-700">
              Awarded to: <strong>{rfp.awardedContractor.businessName || rfp.awardedContractor.contactName}</strong>
            </p>
          )}
        </div>
        <button
          className="text-xs text-blue-600 hover:underline whitespace-nowrap"
          onClick={() => setExpanded(!expanded)}
        >
          {expanded ? "Collapse" : "Details"}
        </button>
      </div>

      {expanded && (
        <div className="mt-3 space-y-3">
          {/* Deadline */}
          {rfp.deadline && (
            <p className="text-xs text-slate-600">
              Deadline: <strong>{formatDate(rfp.deadline)}</strong>
            </p>
          )}

          {/* Invites */}
          {rfp.invites?.length > 0 && (
            <div>
              <p className="text-xs font-medium text-slate-600 mb-1">Invites ({rfp.invites.length}):</p>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-slate-100 text-left font-medium text-slate-500">
                      <th className="py-1 pr-3">Contractor</th>
                      <th className="py-1 pr-3">Status</th>
                      <th className="py-1 pr-3">Sent At</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rfp.invites.map((inv) => (
                      <tr key={inv.id} className="border-b border-slate-50">
                        <td className="py-1 pr-3">
                          {inv.contractorId ? (
                            <Link href={`/manager/people/vendors/${inv.contractorId}`} className="text-indigo-600 hover:underline">
                              {inv.contractor?.businessName || inv.contractorId?.slice(0, 8)}
                            </Link>
                          ) : (inv.contractor?.businessName || "—")}
                        </td>
                        <td className="py-1 pr-3">
                          <InviteStatusPill status={inv.status} />
                        </td>
                        <td className="py-1 pr-3">{formatDate(inv.sentAt)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Quotes */}
          {rfp.quotes?.length > 0 && (
            <div>
              <p className="text-xs font-medium text-slate-600 mb-1">Quotes ({rfp.quotes.length}):</p>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-slate-100 text-left font-medium text-slate-500">
                      <th className="py-1 pr-3">Contractor</th>
                      <th className="py-1 pr-3">Amount</th>
                      <th className="py-1 pr-3">Submitted</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rfp.quotes.map((q) => (
                      <tr key={q.id} className="border-b border-slate-50">
                        <td className="py-1 pr-3">
                          {q.contractorId ? (
                            <Link href={`/manager/people/vendors/${q.contractorId}`} className="text-indigo-600 hover:underline">
                              {q.contractor?.businessName || q.contractorId?.slice(0, 8)}
                            </Link>
                          ) : (q.contractor?.businessName || "—")}
                        </td>
                        <td className="py-1 pr-3 font-mono">CHF {q.amountCents ? (q.amountCents / 100).toFixed(2) : "—"}</td>
                        <td className="py-1 pr-3">{formatDate(q.submittedAt)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function InviteStatusPill({ status }) {
  const colors = {
    PENDING: "bg-yellow-50 text-yellow-700 border-yellow-200",
    SENT: "bg-blue-50 text-blue-700 border-blue-200",
    ACCEPTED: "bg-green-50 text-green-700 border-green-200",
    DECLINED: "bg-red-50 text-red-700 border-red-200",
  };
  return (
    <span className={`inline-block rounded-full border px-2 py-0.5 text-xs font-medium ${colors[status] || colors.PENDING}`}>
      {status}
    </span>
  );
}

function formatDate(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("de-CH");
}
